start_time=`date +%s`

. ~/.bash_alias
. ~/.bash_functions
. ~/.bash_secret

end_time=`date +%s` && echo '[bashinit] included ' $((end_time - start_time))

#set -euo pipefail

NAME='HOME'
ON_KEYCHAIN=false

shopt -u histappend   # .bash_history追記モードは不要なのでOFFに
shopt -s checkwinsize

# alias
export EDITOR=vim
export GIT_EDITOR=vim
export IGNOREEOF=1 # 間違ってCtl+dしても3回は許してくれる
export FIGNORE=".bak:.o:~:.pyc" # 補完時に無視するsuffix
export HISTTIMEFORMAT='%y/%m/%d %H:%M:%S  '
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoreboth # 最後のhistと一緒は無視＆最初がスペースも無視
export HISTIGNORE=?:??:???:exit
export HISTSIZE=10000000000000  # 履歴のMAX保存数を指定
export GIT_COMMITTER_EMAIL=nobjas@gmail.com
export GIT_AUTHOR_EMAIL=nobjas@gmail.com

# PATH
export PATH="$(brew --prefix coreutils)/libexec/gnubin:~/.bin:/usr/local/sbin:~/.bin/mongodb:~/.composer/vendor/bin:~/.bin/flex_sdk/bin:$PATH"
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"

end_time=`date +%s` && echo '[bashinit] exports ' $((end_time - start_time))

#hub
if which hub > /dev/null; then eval "$(hub alias -s)"; else echo "please 'brew install hub'" ; fi

#pyenv

# http://qiita.com/noblejasper/items/cc9332cfdd9cf450d745
export CFLAGS="-I$(brew --prefix openssl)/include"
export LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix sqlite3)/lib"
export CPPFLAGS="-I$(brew --prefix sqlite3)/include"

if which pyenv > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# save history of screen
function share_history {  # 以下の内容を関数として定義
    history -a  # .bash_historyに前回コマンドを1行追記
    history -c  # 端末ローカルの履歴を一旦消去
    history -r  # .bash_historyから履歴を読み込み直す
}
export PROMPT_COMMAND='share_history'  # 上記関数をプロンプト毎に自動実施

# Homebrew Cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# Homebrew bash-completion
[[ -r `brew --prefix`"/etc/profile.d/bash_completion.sh" ]] && . `brew --prefix`"/etc/profile.d/bash_completion.sh"

if [ -f $BASH_COMPLETION_DIR/git-completion.bash ]; then
    PS1='\[\e[0;37m\]${NAME}\[\e[0;37m\][\t]\[\e[0;37m\]: \[\e[1;37m\]\w\n\[\e[1;33m\]h:\! j:\j\[\e[0;36m\]$(__git_ps1) \[\e[0;34m\]\$\[\e[m\] '
else
    PS1='\[\e[0;37m\]${NAME}\[\e[0;37m\][\t]\[\e[0;37m\]: \[\e[1;37m\]\w\n\[\e[1;33m\]h:\! j:\j \[\e[0;34m\]\$\[\e[m\] '
fi

# Git2.9のキレイなdiffを出すためのconfig - Qiita http://qiita.com/takyam/items/d6afacc7934de9b0e85e
export PATH=$PATH:/usr/local/share/git-core/contrib/diff-highlight

end_time=`date +%s` && echo '[bashinit] hub, pyenv, cask ' $((end_time - start_time))


# keychain
if ${ON_KEYCHAIN}; then
    unset SSH_AUTH_SOCK
    HOST_NAME="nobjas-pc-20140608"
    keychain ~/.ssh/id_rsa ~/.ssh/id_dsa ~/.ssh/conoha.key --host $HOST_NAME
    if [ -f ~/.keychain/$HOST_NAME-sh ]; then
        source ~/.keychain/$HOST_NAME-sh
    fi
fi

# bash version 4
if [ "`echo $BASH_VERSION | cut -b 1`" -eq "4" ]; then
    shopt -s dirspell # 入力補完時にディレクトリ名のスペルミスを修正するdirspel
    shopt -s autocd   # ディレクトリ名を入力するだけでカレントディレクトリを変更できるautocd
    shopt -s globstar # サブディレクトリを再帰的にファイル検索するglobstar
    shopt -s cdspell  # cdするときディレクトリ名をよしなに修正する。
    export PROMPT_DIRTRIM=3 # PS1が短くなる
fi

# enhancd
if [ -f ~/.enhancd/init.sh ]; then
    source ~/.enhancd/init.sh
    export ENHANCD_FILTER=fzf:peco:fzy;
fi


## direnv
eval "$(direnv hook bash)"

## anyenv
eval "$(anyenv init -)"

## rbenv
eval "$(rbenv init -)"

## ndenv
eval "$(nodenv init -)"

# ## goenv
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"
export PATH="$GOROOT/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export GOPATH="$HOME/.go"


end_time=`date +%s` && echo '[bashinit] keychain, Heroku Toolbelt, rbenv, ndenv, goenv' $((end_time - start_time))


# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/iwai-yudai/git/noblejasper/metronome/node_modules/tabtab/.completions/serverless.bash ] && . /Users/iwai-yudai/git/noblejasper/metronome/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/iwai-yudai/git/noblejasper/metronome/node_modules/tabtab/.completions/sls.bash ] && . /Users/iwai-yudai/git/noblejasper/metronome/node_modules/tabtab/.completions/sls.bash

end_time=`date +%s` && echo '[bashinit] direnv, tabtab, perlbrew' $((end_time - start_time))

# flutter
export PATH="$PATH:/Applications/flutter/bin"
# android sdk from brew cask
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_HOME="/Users/iwai-yudai/Library/Android/sdk"
export PATH="${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"

source ~/enhancd/init.sh
