### Project specific config ###
language: generic

os: linux

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

after_script:
  # The Atom CI script doesn't support having ESLint as a direct dependency,
  # as such it doesn't run linting automatically for us.
  - npm run lint

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

dist: trusty

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
