(eval-when-compile    (require 'color-theme))
(defun nobjas-color-theme ()
  "Color theme by 岩井 雄大, created 2010-08-29."
  (interactive)
  (color-theme-install
   '(nobjas-color-theme
     ((background-color . "black")
      (background-color-at-point . "black")
      (background-mode . dark)
      (border-color . "yellow")
      (cursor-color . "snow4")
      (foreground-color . "white")
      (mouse-color . "white"))
     ;; ((ac-fuzzy-cursor-color . "red")
     ;;  (anything-show-completion-face . highlight)
     ;;  (compilation-message-face . underline)
     ;;  (list-matching-lines-buffer-name-face . underline)
     ;;  (list-matching-lines-face . match)
     ;;  (moccur-maximum-displayed-with-color . 500)
     ;;  (php-default-face . default)
     ;;  (sense-region-selection-base-face . sense-region-selection-base-face)
     ;;  (snippet-bound-face . bold)
     ;;  (snippet-field-face . highlight)
     ;;  (tags-tag-face . default)
     ;;  (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 240 :width normal :foundry "apple" :family "Inconsolata"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (anything-bmkext-file ((t (:foreground "Deepskyblue2"))))
     (anything-bmkext-gnus ((t (:foreground "magenta"))))
     (anything-bmkext-info ((t (:foreground "green"))))
     (anything-bmkext-man ((t (:foreground "Orange4"))))
     (anything-bmkext-no--file ((t (:foreground "grey"))))
     (anything-bmkext-w3m ((t (:foreground "yellow"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-dired-symlink-face ((t (:foreground "DarkOrange"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (:foreground "grey90" :background "grey20" :box (:line-width -1 :style released-button) :weight normal))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-match ((t (:background "green3"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "yellow"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "grey47"))))
     (change-log-conditionals ((t (:foreground "yellow"))))
     (change-log-date ((t (:foreground "RoyalBlue3"))))
     (change-log-email ((t (:foreground "yellow"))))
     (change-log-file ((t (:foreground "Yellow"))))
     (change-log-function ((t (:foreground "yellow"))))
     (change-log-list ((t (:foreground "turquoise3"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (clmemo-inline-date-face ((t (:foreground "yellow"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "gold2"))))
     (compilation-error ((t (:bold t :weight bold :foreground "yellow"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "yellow"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Inconsolata" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 240))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "snow4"))))
     (dired-directory ((t (:foreground "Yellow"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "yellow"))))
     (dired-header ((t (:foreground "gold2"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :weight bold :foreground "yellow"))))
     (dired-perm-write ((t (:foreground "grey47"))))
     (dired-symlink ((t (:foreground "turquoise3"))))
     (dired-warning ((t (:bold t :weight bold :foreground "yellow"))))
     (elscreen-tab-background-face ((t (:background "black"))))
     (elscreen-tab-control-face ((t (:background "white" :foreground "black" :underline t))))
     (elscreen-tab-current-screen-face ((t (:background "white" :foreground "black"))))
     (elscreen-tab-other-screen-face ((t (:background "blue" :foreground "black" :underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:foreground "black" :background "yellow"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "goldenrod"))))
     (font-lock-comment-delimiter-face ((t (:foreground "grey47"))))
     (font-lock-comment-face ((t (:foreground "grey47"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightGoldenrod2"))))
     (font-lock-function-name-face ((t (:foreground "Yellow"))))
     (font-lock-keyword-face ((t (:foreground "turquoise3"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "goldenrod"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "RoyalBlue3"))))
     (font-lock-type-face ((t (:foreground "gold2"))))
     (font-lock-variable-name-face ((t (:foreground "yellow"))))
     (font-lock-warning-face ((t (:bold t :foreground "yellow" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (header-line ((t (:weight normal :box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "yellow" :foreground "black"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (iswitchb-current-match ((t (:foreground "Yellow"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "yellow"))))
     (iswitchb-single-match ((t (:foreground "grey47"))))
     (iswitchb-virtual-matches ((t (:foreground "goldenrod"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "gold2" :foreground "black"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "green3"))))
     (menu ((t (nil))))
     (minibuf-isearch-comp-face ((t (:background "navy" :underline t))))
     (minibuf-isearch-face ((t (:bold t :background "blue" :underline t :weight bold))))
     (minibuffer-prompt ((t (:foreground "cyan1"))))
     (moccur-current-line-face ((t (:underline t))))
     (moccur-face ((t (:bold t :background "light grey" :foreground "Black" :weight bold))))
     (mode-line ((t (:background "grey19" :foreground "yellow" :box (:line-width -1 :style released-button) :weight normal))))
     (mode-line-buffer-id ((t (nil))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey19" :foreground "grey51" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mouse ((t (:background "white"))))
     (my-sequence-face ((t (:background "bisque" :foreground "blue"))))
     (next-error ((t (:foreground "blue" :background "RosyBrown1"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "RosyBrown1" :foreground "blue"))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:bold t :background "SkyBlue" :foreground "Black" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "gray20" :foreground "azure3" :weight bold))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sense-region-face ((t (:background "RosyBrown1" :foreground "blue"))))
     (sense-region-offset-face ((t (nil))))
     (sense-region-rectangle-face ((t (nil))))
     (sense-region-region-face ((t (:background "RosyBrown1" :foreground "blue"))))
     (sense-region-selection-base-face ((t (:background "#666688"))))
     (sense-region-selection-highlight-face ((t (nil))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "grey17"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Inconsolata" :foundry "apple" :width normal :weight normal :slant normal :background "lightyellow" :foreground "black" :height 240))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:slant normal :weight normal :height 240 :width normal :foundry "apple" :family "Inconsolata"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(nobjas-color-theme  "Nobjas Theme" "noble jasper"))